### ISSUE TITLE
Upgrading rxdart to the latest

### ISSUE THREAD

**Issue by johnbland-wf** [brianegan/dart_redux_epics#1]
Is there a technical reason why rxdart is limited to `0.14.x`? Can it be upgraded without a major haul?

We're ok doing the work. I just wanted to check.

**Comment by zoechi** [comment]
That's actually how it should be. 
For semantic versioning minor version increments are used for breaking changes for versions < 1.0.0.
Non-breaking changes should just update the build number.
For versions > 1.0.0 the major version is required to be incremented for breaking changes.

**Comment by johnbland-wf** [comment]
You state the problem clearly. As you noticed on https://github.com/ReactiveX/rxdart/issues/109, I'm hoping this can get updated to a 1.0 so this limited range isn't required anymore.
