### ISSUE TITLE
How to dispatch multiple actions from an Epic

### ISSUE THREAD

**Issue by cubissimo** [brianegan/dart_redux_epics#22]
Is there a pattern to dispatch multiple actions from an Epic?

```
return Observable(actions)
        .ofType(TypeToken<SearchAction>())
        .debounce(Duration(milliseconds: 300))
        .switchMap((SearchAction action) {
      return _getResults(store, action)
          .map((result) => OnSearchResult(result))
        //want to dispatch a analytics action here something like
        // .map((result) => [OnSearchResult(result), SearchAnalyticAction(result)])
          .takeUntil(actions.where((action) => action is CancelSearchAction));
```
is there a way to do that? Or is better to have 2 separeted epics listen same action (SearchAction)?

tks

**Comment by brianegan** [comment]
Hey there -- Yep, you have total control of what's emitted from the Stream! In this case, you're only emitting one thing from this stream: A list of actions.

Instead, you need to emit two items! You have a few ways to do that, but the easiest for this case will be using the `expand` operator, which will emit all items in the provided List as an individual event: https://docs.flutter.io/flutter/dart-async/Stream/expand.html


The example becomes:

```
return Observable(actions)
        .ofType(TypeToken<SearchAction>())
        .debounce(Duration(milliseconds: 300))
        .switchMap((SearchAction action) {
      return _getResults(store, action)
          .expand((result) => [OnSearchResult(result), SearchAnalyticAction(result)])
          .takeUntil(actions.where((action) => action is CancelSearchAction));
```

**Comment by cubissimo** [comment]
Superb! Thanks @brianegan
