### ISSUE TITLE
Not compatible with latest rxdart

### ISSUE THREAD

**Issue by sokolej79** [brianegan/dart_redux_epics#26]
So, because app depends on both redux_epics ^0.10.4 and rxdart ^0.21.0, version solving failed

**Comment by andrasferenczi** [comment]
It looks like the `0.10.5` [version](https://github.com/brianegan/dart_redux_epics/commit/54e5495c06337c155d45008c8e6e31ae00c0362f) is ready, but is not yet available on the pub.

**Comment by andrasferenczi** [comment]
@brianegan Sorry to spam you with this, but could you help us out with this?

**Comment by brianegan** [comment]
Hey @andrasferenczi -- sure thing! Sorry about that, I'll publish a new version with the latest Rx shortly.

**Comment by brianegan** [comment]
Again, apologies for the delay here. Now published as version 0.10.6 with compatibility for the latest RxDart
