### ISSUE TITLE
Unhandled Exception: type 'SetEventItemFailAction' is not a subtype of type 'FutureOr<UpdateTaskAction>'

### ISSUE THREAD

**Issue by aliyoge** [brianegan/dart_redux_epics#38]
Here is my code:

```dart
Stream<dynamic> setEventItemsEffect(
    Stream<dynamic> actions, EpicStore<AppState> store) {
  return actions
      .whereType<SetEventItemAction>()
      .asyncMap((action) => handleEventItems(action.task)
        .then((res) => UpdateTaskAction(task: action.task)
        .catchError((_) => SetEventItemFailAction(task: action.task))
  );
}
```

When to `catchError`, this code get error `Unhandled Exception: type 'SetEventItemFailAction' is not a subtype of type 'FutureOr<UpdateTaskAction>'`

When I change code to this according to #30 :

```dart
Stream<dynamic> setEventItemsEffect(
    Stream<dynamic> actions, EpicStore<AppState> store) {
  return actions
      .whereType<SetEventItemAction>()
      .asyncMap((action) => Stream<dynamic>.fromFuture(handleEventItems(action.task)
        .then((res) => UpdateTaskAction(task: action.task)
        .catchError((_) => SetEventItemFailAction(task: action.task)))
  );
}
```

The error is gone, but the type goes like this. 
`Action: Instance of '_ControllerStream<dynamic>'`

or:

```dart
Stream<dynamic> setEventItemsEffect(
    Stream<dynamic> actions, EpicStore<AppState> store) {
  return actions
      .whereType<SetEventItemAction>()
      .asyncMap((action) => Stream<UpdateTaskAction>.fromFuture(handleEventItems(action.task)
        .then((res) => UpdateTaskAction(task: action.task)
        .catchError((_) => SetEventItemFailAction(task: action.task)))
  );
}
```

The type goes like this. 
`Action: Instance of '_ControllerStream<dynamic>'`

**Comment by aliyoge** [comment]
Update:

I solved this problem in this way:

```dart
Stream<dynamic> setEventItemsEffect(
    Stream<dynamic> actions, EpicStore<AppState> store) {
  return actions
      .whereType<SetEventItemAction>()
      .asyncMap((action) => handleEventItems(action.task)
        .then<dynamic>((res) => UpdateTaskAction(task: action.task)
        .catchError((_) => SetEventItemFailAction(task: action.task))
  );
}
```

Is there a better way? @brianegan

**Comment by brianegan** [comment]
Hey there -- Futures can only return one type of Object. In your original example, Dart is inferring that you want to create a `Future<UpdateTaskAction>`, but if an error occurs you're trying to return a  different type: `SetEventItemFailAction`. The future cannot do that -- it can only return one type!

Therefore, you have two options:

  1. Make each of these actions implement a common parent interface
  2. Use `Object` or `dynamic` as the "root" type -- which is what Redux does, and what you've done!

Therefore, the way you've solved it is completely appropriate, but hope this explanation helps you understand why :)

**Comment by aliyoge** [comment]
> Hey there -- Futures can only return one type of Object. In your original example, Dart is inferring that you want to create a `Future<UpdateTaskAction>`, but if an error occurs you're trying to return a different type: `SetEventItemFailAction`. The future cannot do that -- it can only return one type!
> 
> Therefore, you have two options:
> 
> 1. Make each of these action classes implement a common parent interface
> 2. Use `Object` or `dynamic` as a default parent interface -- which is what Redux does, and what you've done!
> 
> Therefore, the way you've solved it is completely appropriate, but hope this explanation helps you understand why :)

Thank you very much for your explanation.
