### ISSUE TITLE
Need update to redux 3.0.0

### ISSUE THREAD

**Issue by Paul-Todd** [brianegan/dart_redux_epics#8]
Hi, at the moment the dependencies specify that it will use Redux up to but not including Redux 3.0.0 and this is causing a problem with the dependency checker in Dart nesting too deep to try to work out a compatible version.

Can we get the version pushed up to include 3.0.0?

FWIW I have the following dependencies:

```
redux: ^3.0.0
rxdart: ^0.16.5
flutter_redux: ^0.5.0
```

**Comment by brianegan** [comment]
@Paul-Todd Thanks! I'm on the case. Look for an update in the next day or so!

**Comment by brianegan** [comment]
0.9.0 has been released with Redux 3.0.0 support
